<?php
/**
 * Barzahlen Payment Module for Magento
 *
 * @category    ZerebroInternet
 * @package     ZerebroInternet_Barzahlen
 * @copyright   Copyright (c) 2015 Cash Payment Solutions GmbH (https://www.barzahlen.de)
 * @author      Alexander Diebler
 * @author      Martin Seener
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL-3.0)
 */
?>

<?php $_code = $this->getMethodCode(); ?>
<ul class="form-list" id="payment_form_<?php echo $_code ?>" style="display:none">
  <li>
    <?php
      echo '<div id="barzahlen_description">';
      echo '<img id="barzahlen_special" src="https://cdn.barzahlen.de/images/barzahlen_special.png" style="float: right; margin-left: 10px; max-width: 180px; max-height: 180px;">';
      echo $this->__('bz_frnt_info') . "<br><br>";
      echo $this->__('bz_frnt_partner') . "&nbsp;";
      for($i = 1; $i <= 10; $i++) {
        $count = str_pad($i,2,"0",STR_PAD_LEFT);
        echo '<img src="https://cdn.barzahlen.de/images/barzahlen_partner_'.$count.'.png" alt="" style="height: 1em; vertical-align: -0.1em; display: inline">';
      }
      echo '</div>';
    ?>
  </li>
</ul>
<script src="https://cdn.barzahlen.de/js/selection.js"></script>