<?php
/**
 * Barzahlen Payment Module
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to info@barzahlen.de so we can send you a copy immediately.
 *
 * @category    ZerebroInternet
 * @package     ZerebroInternet_Barzahlen
 * @copyright   Copyright (c) 2012 Zerebro Internet GmbH (http://www.barzahlen.de)
 * @author      Martin Seener
 * @author      Alexander Diebler
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL-3.0)
 */
?>

<img src="http://cdn.barzahlen.de/images/barzahlen_logo.png" width="126" alt="Barzahlen Logo"  class="v-middle" />&nbsp;&nbsp;&nbsp;
<a href="<?php echo $this->getPaymentAcceptanceMarkHref()?>" target="_blank" style="color: #63A924; font-size: 0.9em;"><?php echo Mage::helper('barzahlen')->__('bz_frnt_whatis') ?></a>