<?php
/**
 * Barzahlen Payment Module
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to info@barzahlen.de so we can send you a copy immediately.
 *
 * @category    ZerebroInternet
 * @package     ZerebroInternet_Barzahlen
 * @copyright   Copyright (c) 2012 Zerebro Internet GmbH (http://www.barzahlen.de)
 * @author      Martin Seener
 * @author      Alexander Diebler
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL-3.0)
 */

// Get Checkout Information
$session = Mage::getSingleton('checkout/session');
$orderId = $session->getLastRealOrderId();
?>

<div class="page-title" style="padding:0; margin:0; margin-bottom: 10px;">
    <h1 style="padding:0; margin:0; margin-bottom: 10px;">
      <?php echo $session->getResponse() == 200 ? $this->__('bz_frnt_processing_orderreceived') : $this->__('bz_frnt_processing_transactionerror'); ?>
    </h1>
</div>

<?php
  if($session->getResponse() != 200) {
    echo "<h2 class=\"sub-title\">". $this->__('bz_frnt_processing_erroroccured') ."</h2>";
  }
  else {
?>
<iframe src="<?php echo($session->getBzPaymentSlipLink()); ?>" width="0" height="1" frameborder="0"></iframe>
<img src="http://cdn.barzahlen.de/images/barzahlen_logo.png" height="57" width="168" alt="" style="padding:0; margin:0; margin-bottom: 10px;"/>
<hr/>
<br/>
<div style="width:100%;">

  <div style="position: relative; float: left; width: 180px; text-align: center;">
    <a href="<?php echo $session->getBzPaymentSlipLink(); ?>" target="_blank" style="color: #63A924; text-decoration: none; font-size: 1.2em;">
      <img src="http://cdn.barzahlen.de/images/barzahlen_checkout_success_payment_slip.png" height="192" width="126" alt="" style="margin-bottom: 5px;"/><br/>
      <strong>Download PDF</strong>
    </a>
  </div>

  <h1 style="font-weight: bold; color: #63A924;"><?php echo $this->__('bz_frnt_processing_title'); ?></h1>
  <h2><?php echo $this->__('bz_frnt_processing_orderno', $this->escapeHtml($orderId)); ?></h2><br/>
  <p><?php echo $session->getBzInfotext1(); ?></p>
  <p><?php echo $session->getBzExpirationNote(); ?></p>
  <div style="width:100%;">
    <div style="position: relative; float: left; width: 50px;"><img src="http://cdn.barzahlen.de/images/barzahlen_mobile.png" height="52" width="41" alt=""/></div>
    <p><?php echo $session->getBzInfotext2(); ?></p>
  </div>

<br style="clear:both;" /><br/>
</div>
<hr/>

<?php } ?>

<div class="buttons-set">
  <button type="button" class="button" title="<?php echo $this->__('bz_frnt_processing_cntshp'); ?>" onclick="window.location='<?php echo $this->getUrl(); ?>'">
    <span><span><?php echo $this->__('bz_frnt_processing_cntshp'); ?></span></span>
  </button>
</div>