<?php
/**
 * Barzahlen Payment Module
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to info@barzahlen.de so we can send you a copy immediately.
 *
 * @category    ZerebroInternet
 * @package     ZerebroInternet_Barzahlen
 * @copyright   Copyright (c) 2012 Zerebro Internet GmbH (http://www.barzahlen.de)
 * @author      Martin Seener
 * @author      Alexander Diebler
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL-3.0)
 */

// Get Checkout Information
$session = Mage::getSingleton('checkout/session');
?>

<div class="page-title" style="padding:0; margin:0; margin-bottom: 10px;">
    <h1 style="padding:0; margin:0; margin-bottom: 10px;">
      <?php echo $session->getResponse() == 200 ? $this->__('bz_frnt_processing_orderreceived') : $this->__('bz_frnt_processing_transactionerror'); ?>
    </h1>
</div>

<?php
  if($session->getResponse() != 200) {
    echo "<h2 class=\"sub-title\">". $this->__('bz_frnt_processing_erroroccured') ."</h2>";
  }
  else {
    echo $session->getBzInfotext1();
  }
?>

<div class="buttons-set">
  <button type="button" class="button" title="<?php echo $this->__('bz_frnt_processing_cntshp'); ?>" onclick="window.location='<?php echo $this->getUrl(); ?>'">
    <span><span><?php echo $this->__('bz_frnt_processing_cntshp'); ?></span></span>
  </button>
</div>